spring:
  datasource:
    url: jdbc:mariadb://localhost:4001/noticeboard
    username: gocoding
    password: gocoding
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format=sql: true
    show-sql: true

server:
  port: 8081