spring:
  datasource:
    url: jdbc:mariadb://localhost:4001/noticeboard
    username: gocoding
    password: gocoding
    driver-class-name: org.mariadb.jdbc.Driver

  #Thymeleaf Cache Setting
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format=sql: true
    show-sql: true

server:
  port: 8081

#Security log level Setting
logging:
  level:
    org:
      springframework:
        security: debug